services:
  luna:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      BOT_PATH: /bot
    volumes:
      - ${BOT_HOST_PATH}:/bot
    restart: unless-stopped
